
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace MyGuiCsProject {
    using Terminal.Gui;
    
    
    public partial class MyView {
        
        public MyView() {
            InitializeComponent();

            button1.Accept += (s, e) =>
            {
                e.Handled = true;
                return MessageBox.Query("Hello", "Hello There!", "Ok");
            };
        }
    }
}
